# Generated by Django 6.1 on 2026-09-01 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(db_index=True, help_text='E.164, exactly as the verified Firebase token spelled it.', max_length=20, unique=True)),
                ('firebase_uid', models.CharField(blank=True, default='', help_text='Latest Firebase uid seen for this number. Diagnostic, not a key.', max_length=128)),
                ('last_login_at', models.DateTimeField(blank=True, help_text='Set by POST /api/auth/session/, not by every authenticated request.', null=True)),
                ('user', models.OneToOneField(help_text="The auth.User row that owns this identity's portfolios.", on_delete=django.db.models.deletion.CASCADE, related_name='app_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'app user',
                'verbose_name_plural': 'app users',
                'ordering': ['phone_number'],
            },
        ),
    ]
