# Generated by Django 6.1 on 2026-08-27 02:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.CharField(choices=[('price_move_pct', 'Price move %'), ('var_breach', 'VaR breach'), ('drawdown_pct', 'Drawdown %'), ('concentration_pct', 'Concentration %'), ('stop_loss', 'Stop loss')], max_length=32)),
                ('operator', models.CharField(choices=[('gt', 'greater than (>)'), ('gte', 'greater than or equal (>=)'), ('lt', 'less than (<)'), ('lte', 'less than or equal (<=)')], max_length=3)),
                ('threshold', models.DecimalField(decimal_places=4, help_text='Percent as a whole number (5 = 5%); stop_loss is an absolute price.', max_digits=18)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['portfolio', 'metric'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triggered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('value', models.DecimalField(decimal_places=4, help_text='The metric value observed at trigger time.', max_digits=18)),
                ('message', models.TextField(help_text='Human-readable summary shown in the alert feed.')),
                ('acknowledged', models.BooleanField(default=False)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='alerts.alertrule')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['active', 'metric'], name='rule_active_metric_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['acknowledged', '-triggered_at'], name='event_ack_ts_idx'),
        ),
    ]
