# Generated by Django 6.1 on 2026-08-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertevent',
            name='value',
            field=models.DecimalField(decimal_places=4, help_text='The metric value observed at trigger time, in the SAME units as rule.threshold - so the two are directly comparable in the feed.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='metric',
            field=models.CharField(choices=[('var_historical', 'VaR (historical)'), ('max_drawdown', 'Max drawdown'), ('annualized_volatility', 'Volatility (annualised)'), ('hhi', 'Concentration (HHI)'), ('concentration', 'Largest holding weight'), ('beta', 'Beta vs benchmark')], max_length=32),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='threshold',
            field=models.DecimalField(decimal_places=4, help_text='Percent as a whole number for var_historical, max_drawdown, annualized_volatility and concentration (5 = 5%, -15 = -15%); the bare number for hhi and beta.', max_digits=18),
        ),
    ]
