# Generated by Django 6.1 on 2026-08-27 02:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('base_currency', models.CharField(default='INR', help_text='ISO 4217 code. All holdings are assumed quoted in this currency.', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(db_index=True, help_text='yfinance symbol. Indian equities use the .NS suffix, e.g. RELIANCE.NS', max_length=32)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('avg_buy_price', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('buy_date', models.DateField(help_text='Date the position was opened.')),
                ('asset_type', models.CharField(choices=[('EQUITY', 'Equity'), ('ETF', 'ETF'), ('MUTUAL_FUND', 'Mutual fund'), ('BOND', 'Bond'), ('CASH', 'Cash'), ('CRYPTO', 'Crypto'), ('OTHER', 'Other')], default='EQUITY', max_length=16)),
                ('sector', models.CharField(blank=True, default='', help_text="Free text for now, e.g. 'Energy'. Drives sector concentration later.", max_length=64)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['portfolio', 'ticker'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(db_index=True, max_length=32)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price', models.DecimalField(decimal_places=4, help_text='Execution price per unit.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_portfolio_per_user_name'),
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['ticker'], name='holding_ticker_idx'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(fields=('portfolio', 'ticker'), name='uniq_holding_per_portfolio_ticker'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['portfolio', 'ticker', 'timestamp'], name='txn_pf_ticker_ts_idx'),
        ),
    ]
