"""
The only module in the project that talks to Google Gemini.

Same containment rule as `payments/gateway.py` for razorpay, `accounts/
firebase.py` for firebase-admin and `marketdata/providers.py` for yfinance
(architecture rule 4). Everything else in `insights/` calls `generate()`, which
is the ONE function the test suite patches to stay off the network, and the
one file that changes if the model or the vendor ever does.

WHY REST AND NOT THE SDK
------------------------
`google-generativeai` is in the venv but is deprecated upstream and was never
in requirements.txt. The API itself is one JSON POST, and calling it directly
buys three things the SDK makes awkward: an explicit per-request timeout, one
mockable seam, and a hard guarantee about where the key goes (below).

WHAT IS SECRET HERE
-------------------
`GEMINI_API_KEY` is sent in the `x-goog-api-key` HEADER, never as a `?key=`
query parameter. That is not a style choice: `requests` includes the URL in the
text of every exception it raises, and a key in the URL would land in the log
line `custom_exception_handler` writes for an unhandled error. The header is
not part of any exception message, so the key stays in the process. It is not
returned by any endpoint, not rendered anywhere, and not logged - not even
truncated.

WHAT IS AND IS NOT RETRIED
--------------------------
Nothing is. A 429 from the free tier is a per-minute quota, and retrying into
it is how a quota becomes a block. The user's Retry button is the retry, and
the service layer turns every failure below into a calm "unavailable right
now" rather than a 500 - see `insights/services.py`.
"""

from __future__ import annotations

import logging

import requests
from django.conf import settings

logger = logging.getLogger(__name__)

API_ROOT = "https://generativelanguage.googleapis.com/v1beta/models"

#: The categories an insight may carry. This list is handed to the model as a
#: JSON schema `enum`, so the response cannot invent a sixth - and the service
#: layer checks it again on the way out, because a schema is a request to the
#: model, not a proof.
CATEGORIES = ("gain", "loss", "risk", "diversification", "general")

#: The response shape the model is constrained to. `responseMimeType` plus
#: `responseSchema` makes Gemini emit exactly this JSON and nothing around it
#: (no prose, no markdown fences), which is what lets the parser be strict.
RESPONSE_SCHEMA = {
    "type": "OBJECT",
    "properties": {
        "insights": {
            "type": "ARRAY",
            "items": {
                "type": "OBJECT",
                "properties": {
                    "category": {"type": "STRING", "enum": list(CATEGORIES)},
                    "text": {"type": "STRING"},
                },
                "required": ["category", "text"],
            },
        }
    },
    "required": ["insights"],
}


# ---------------------------------------------------------------------------
# Failures.
#
# One base class, so the service layer can catch "Gemini did not answer" in a
# single clause, and subclasses so the message it shows can say WHY without
# ever quoting the upstream body (which could carry the request back).
# ---------------------------------------------------------------------------
class GeminiError(Exception):
    """Base: the model produced no usable answer."""

    reason = "unavailable"


class GeminiNotConfigured(GeminiError):
    """No API key in this process. A server fault, not a user one."""

    reason = "not_configured"


class GeminiRateLimited(GeminiError):
    """HTTP 429 - the free-tier quota is exhausted for the moment."""

    reason = "rate_limited"


class GeminiUnavailable(GeminiError):
    """Timeout, connection failure, or a 5xx from the API."""

    reason = "unavailable"


class GeminiBadResponse(GeminiError):
    """A 2xx whose body was not the shape we asked for, or was blocked."""

    reason = "bad_response"


def is_configured() -> bool:
    """True when a key is present. The value is never returned or logged."""
    return bool(settings.GEMINI_API_KEY)


def model_name() -> str:
    """Which model the insights are generated by. Reported in the response."""
    return settings.GEMINI_MODEL


def generate(prompt: str, *, temperature: float = 0.3) -> str:
    """
    One `generateContent` call. Returns the model's text - a JSON document,
    because the request pins `responseSchema` - or raises a GeminiError.

    Args:
        prompt: the full instruction + data block from `services.build_prompt`.
        temperature: low, deliberately. This is a description of numbers the
            caller already has; creativity here is a synonym for making things
            up. 0.3 keeps the phrasing natural without inventing a holding.

    Raises:
        GeminiNotConfigured: no key.
        GeminiRateLimited:   429.
        GeminiUnavailable:   timeout, connection error, or 5xx.
        GeminiBadResponse:   any other non-2xx (a 400 for a bad model name, a
                             403 for a revoked key), or a 2xx with no text in
                             it (a safety block, an empty candidate list).
    """
    if not is_configured():
        raise GeminiNotConfigured("GEMINI_API_KEY is not set in backend/.env.")

    body = {
        "contents": [{"role": "user", "parts": [{"text": prompt}]}],
        "generationConfig": {
            "temperature": temperature,
            "responseMimeType": "application/json",
            "responseSchema": RESPONSE_SCHEMA,
            # Six insights of two sentences is well under this; the cap is
            # there so a model that ignores "concise" cannot run up the bill.
            "maxOutputTokens": 4096,
        },
    }

    try:
        response = requests.post(
            f"{API_ROOT}/{settings.GEMINI_MODEL}:generateContent",
            headers={
                "x-goog-api-key": settings.GEMINI_API_KEY,
                "Content-Type": "application/json",
            },
            json=body,
            timeout=settings.GEMINI_TIMEOUT_SECONDS,
        )
    except requests.Timeout as exc:
        logger.warning("Gemini timed out after %ss.", settings.GEMINI_TIMEOUT_SECONDS)
        raise GeminiUnavailable("The model took too long to answer.") from exc
    except requests.RequestException as exc:
        # Type name only. The exception text can include the URL, and while the
        # key is not in it, keeping upstream strings out of our logs is the
        # habit that makes that guarantee survive the next refactor.
        logger.warning("Gemini request failed: %s", type(exc).__name__)
        raise GeminiUnavailable("Could not reach the model.") from exc

    if response.status_code == 429:
        logger.warning("Gemini rate limit hit (429).")
        raise GeminiRateLimited("The model's free-tier quota is exhausted for now.")
    if response.status_code >= 500:
        logger.warning("Gemini answered %s.", response.status_code)
        raise GeminiUnavailable(f"The model answered HTTP {response.status_code}.")
    if not response.ok:
        # 400 (bad model name / malformed schema) and 403 (key revoked, API not
        # enabled) are both configuration faults on OUR side. Status only in
        # the log; the body can echo the request.
        logger.error("Gemini rejected the request with HTTP %s.", response.status_code)
        raise GeminiBadResponse(f"The model rejected the request (HTTP {response.status_code}).")

    return _extract_text(response)


def _extract_text(response: requests.Response) -> str:
    """
    The first candidate's text out of a generateContent body.

    Shape: {"candidates": [{"content": {"parts": [{"text": ...}]},
                             "finishReason": "STOP"}, ...]}

    An empty candidate list, or a candidate with no parts, is what a safety
    block or a prompt-level refusal looks like - the request succeeded and the
    model said nothing. That is a GeminiBadResponse, and the finish reason is
    logged (it is a short enum, never user text) because it is the one clue to
    why.
    """
    try:
        payload = response.json()
    except ValueError as exc:
        raise GeminiBadResponse("The model's answer was not JSON.") from exc

    candidates = payload.get("candidates") or []
    if not candidates:
        reason = (payload.get("promptFeedback") or {}).get("blockReason", "no candidates")
        logger.warning("Gemini returned no candidates (%s).", reason)
        raise GeminiBadResponse("The model returned no answer.")

    first = candidates[0]
    parts = (first.get("content") or {}).get("parts") or []
    # Thinking models mark their reasoning parts `thought: true`; those are
    # never the answer. What is left is usually one JSON part, but the model
    # sometimes prefixes it with a prose part ("Here is the JSON:") even under
    # responseMimeType, so the parts are inspected rather than concatenated.
    texts = [
        part["text"]
        for part in parts
        if isinstance(part, dict) and not part.get("thought") and (part.get("text") or "").strip()
    ]
    if not texts:
        logger.warning("Gemini candidate was empty (%s).", first.get("finishReason", "?"))
        raise GeminiBadResponse("The model returned an empty answer.")

    # Prefer the last part that is a JSON document on its own.
    for text in reversed(texts):
        stripped = text.strip()
        if stripped.startswith("{") and stripped.endswith("}"):
            return stripped

    # Salvage: a JSON object somewhere inside prose. The parser downstream
    # still validates it, so an over-eager slice fails there, calmly.
    joined = "".join(texts)
    start, end = joined.find("{"), joined.rfind("}")
    if start != -1 and end > start:
        return joined[start : end + 1]
    return joined
