"""
AI insights API.

Thin, like every other view module: take the id off the URL, resolve whose
portfolio that is, call the service, return the dict. The envelope is applied
by `common.renderers.EnvelopeJSONRenderer`, and the only exceptions that can
leave the service are the data ones `compute_risk` raises, which
`common.exceptions.custom_exception_handler` already renders.

AUTHENTICATED, UNLIKE THE REPORTS
---------------------------------
/api/risk/ and its siblings are still AllowAny with a URL-id fallback (see the
Part 3 TODOs there). This endpoint is not: it spends a per-minute quota on a
third-party model on every call, and an anonymous caller who could point it at
any portfolio id would be spending that quota - and reading that portfolio -
for free. `IsAppUser` makes `request.user` an investor, and
`resolve_portfolio_id` then returns THEIR portfolio whatever the URL says, so
the id in the path is decorative and the answer is always the caller's own.

POST, NOT GET
-------------
It has no body and changes nothing in the database, but it is not idempotent
and not cheap: each call is a fresh model invocation against a rate-limited
quota. GET would invite browsers, proxies and a curious prefetcher to make
that call; POST keeps it to a deliberate click.
"""

from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response

from accounts.permissions import IsAppUser
from accounts.selectors import resolve_portfolio_id
from insights.services import build_ai_insights


@api_view(["POST"])
@permission_classes([IsAppUser])
def ai_insights(request, portfolio_id: int):
    """
    POST /api/insights/<portfolio_id>/

    Plain-English observations about the caller's portfolio, generated by a
    language model from the SAME figures /api/risk/ returns - the holdings as
    valued there, their unrealised P/L, the weights, and the headline metrics.
    Holdings the risk report excluded for want of price data are named as
    unmeasured, never valued.

    Always answers 200 when the portfolio is measurable. If the model cannot be
    reached - no key, a rate limit, a timeout - `available` is false and
    `message` says so; `insights` is then empty. See insights/services.py.

    Every response ends with `disclaimer`. Observations, not advice.
    """
    return Response(build_ai_insights(resolve_portfolio_id(request, portfolio_id)))
