# Generated by Django 6.1 on 2026-09-01 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('razorpay_order_id', models.CharField(db_index=True, help_text='The order this row was created for. Unique: one order, one row.', max_length=64, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, default='', help_text='Set only once a signature has verified. Empty means unpaid.', max_length=64)),
                ('amount', models.PositiveIntegerField(help_text='In paise. ₹9 is 900.')),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='created', max_length=8)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When the signature verified. The clock the 20-minute grant runs on.', null=True)),
                ('consumed', models.BooleanField(db_index=True, default=False, help_text='True once the editing round this paid for has ended.')),
                ('consumed_at', models.DateTimeField(blank=True, help_text='When, and - with services.py - implicitly why.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', 'consumed'], name='payment_user_status_idx')],
            },
        ),
    ]
