# Generated by Django 6.1 on 2026-08-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(db_index=True, max_length=32)),
                ('date', models.DateField()),
                ('close', models.DecimalField(decimal_places=4, max_digits=18)),
            ],
            options={
                'verbose_name': 'price history',
                'verbose_name_plural': 'price history',
                'ordering': ['ticker', '-date'],
                'indexes': [models.Index(fields=['ticker', 'date'], name='history_ticker_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('ticker', 'date'), name='uniq_price_per_ticker_date')],
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(db_index=True, max_length=32)),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('timestamp', models.DateTimeField(help_text='Quote time reported by the provider (UTC).')),
            ],
            options={
                'verbose_name': 'price snapshot',
                'verbose_name_plural': 'price snapshots',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ticker', '-timestamp'], name='snapshot_ticker_ts_idx')],
            },
        ),
    ]
