# Generated by Django 6.1 on 2026-08-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricesnapshot',
            options={'ordering': ['ticker'], 'verbose_name': 'price snapshot', 'verbose_name_plural': 'price snapshots'},
        ),
        migrations.RemoveIndex(
            model_name='pricesnapshot',
            name='snapshot_ticker_ts_idx',
        ),
        migrations.AlterField(
            model_name='pricesnapshot',
            name='ticker',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='pricesnapshot',
            name='timestamp',
            field=models.DateTimeField(help_text='When this price was fetched (UTC).'),
        ),
    ]
